!include <awslib/AWSCommon>
!include <awslib/General/Users>
!include <awslib/Mobile/APIGateway>
!include <awslib/Storage/S3Bucket>
!include <awslib/Compute/Lambda>
!include <awslib/Database/DynamoDBTable>
!include <awslib/Database/RDSAmazonRDSInstance>
!include <awslib/Database/ElastiCacheForRedis>
!include ./C4_Container.iuml

skinparam rectangle<<aws>> {
    Shadowing false
    StereotypeFontSize 11
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam database<<aws_s3>> {
    Shadowing false
    StereotypeFontSize 11
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam database<<aws_dynamo>> {
    Shadowing false
    StereotypeFontSize 11
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam database<<aws_rds>> {
    Shadowing false
    StereotypeFontSize 11
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam database<<aws_elasticcache>> {
    Shadowing false
    StereotypeFontSize 11
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

!unquoted procedure Container_AWS_S3($alias, $label, $descr, $tags="")
database "<$S3Bucket{scale=0.66>\n==$label\n//<size:TECHN_FONT_SIZE>[AWS S3]</size>//\n\n$descr" $toStereos('aws_s3', $tags) as $alias
$tiAddToLegend(aws_s3, $CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $CONTAINER_BORDER_COLOR)
!endprocedure

!unquoted procedure Container_AWS_DynamoDB($alias, $label, $descr, $tags="")
database "<$DynamoDBTable{scale=0.66}>\n==$label\n//<size:TECHN_FONT_SIZE>[AWS DynamoDb]</size>//\n\n$descr" $toStereos('aws_dynamo', $tags) as $alias
$tiAddToLegend(aws_dynamo, $CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $CONTAINER_BORDER_COLOR)
!endprocedure

!unquoted procedure Container_AWS_RDS($alias, $label, $descr, $tags="")
database "<$RDSAmazonRDSinstance{scale=0.66}>\n==$label\n//<size:TECHN_FONT_SIZE>[AWS RDS]</size>//\n\n$descr" $toStereos('aws_rds', $tags) as $alias
$tiAddToLegend(aws_rds, $CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $CONTAINER_BORDER_COLOR)
!endprocedure

!unquoted procedure Container_AWS_ElastiCache($alias, $label, $descr, $tags="")
database "<$ElastiCacheForRedis{scale=0.66}>\n==$label\n//<size:TECHN_FONT_SIZE>[AWS ElasticCache]</size>//\n\n$descr" $toStereos('aws_elasticcache', $tags) as $alias
$tiAddToLegend(aws_elasticcache, $CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $CONTAINER_BORDER_COLOR)
!endprocedure
