!include https://raw.githubusercontent.com/TheIconic/PlantUML-skins/master/src/common.iuml
!include <c4/C4_Container.puml>

!include <tupadr3/common.puml>

!include <tupadr3/font-awesome-5/user.puml>
!include <tupadr3/font-awesome-5/apple.puml>
!include <tupadr3/font-awesome-5/android.puml>
!include <tupadr3/font-awesome-5/mobile.puml>
!include <tupadr3/font-awesome-5/chrome.puml>
!include <tupadr3/font-awesome-5/robot.puml>

!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/bucket/bucket>

!global $TI_CORNER_RADIUS = 15
!global $STEREOTYPE_FONT_SIZE = 11
!global $QUEUE_BG_COLOR = "#EEDD66"
!global $QUEUE_FONT_COLOR = "#666622"
!global $QUEUE_BORDER_COLOR = "#DDCC00"

!unquoted procedure SHOW_DYNAMIC_LEGEND($hideStereotype="true")
!if ($hideStereotype=="true")
hide stereotype
!endif
!$lgd = $showActiveLegendEntries($tagDefaultLegend) + $showActiveLegendEntries($tagCustomLegend)
center footer $lgd
!endprocedure

!function $showActiveLegendEntries($allDefined)
  !$legend = ""
  !$brPos = %strpos($allDefined, "\n")
  !while ($brPos >= 0)
    !$tagStereo = %substr($allDefined, 0, $brPos)
    !$allDefined = %substr($allDefined, $brPos+2)
    !$brPos = %strpos($allDefined, "\n")
    !if (%variable_exists("$" + $tagStereo + "Legend"))
      !$legend = $legend + %get_variable_value("$" + $tagStereo + "LegendEntry")
    !endif
  !endwhile
  !if (%strlen($allDefined)>0)
    !$tagStereo = $allDefined
    !if (%variable_exists("$" + $tagStereo + "Legend"))
      !$legend = $legend + %get_variable_value("$" + $tagStereo + "LegendEntry")
    !endif
  !endif
  !return $legend
!endfunction

skinparam rectangle {
    roundCorner $TI_CORNER_RADIUS
}

skinparam queue {
    Shadowing false
    StereotypeFontSize 11
    StereotypeFontColor #666622
    FontColor $QUEUE_FONT_COLOR
    BackgroundColor $QUEUE_BG_COLOR
    BorderColor $QUEUE_BORDER_COLOR
}

skinparam rectangle<<app>> {
    Shadowing false
    StereotypeFontSize $STEREOTYPE_FONT_SIZE
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $SYSTEM_BG_COLOR
    BorderColor #3C7FC0
}

skinparam frame<<app>> {
    roundCorner 15
    Shadowing false
    StereotypeFontSize $STEREOTYPE_FONT_SIZE
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $SYSTEM_BG_COLOR
    BorderColor #3C7FC0
}

skinparam rectangle<<bot>> {
    Shadowing false
    StereotypeFontSize $STEREOTYPE_FONT_SIZE
    StereotypeFontColor #666622
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam rectangle<<group>> {
    BorderColor white
    BorderThickness 0
}

!function $getQueue($label, $techn, $descr, $sprite)
    !$ftech = ""
    !if ($techn != "")
        !$ftech = '\n//<size:' + $TECHN_FONT_SIZE + '>[' + $techn + ']</size>//'
    !endif
    !if ($descr == "") && ($sprite == "")
        !return '==' + $label + '\n' + $ftech
    !endif
    !if ($descr == "") && ($sprite != "")
        !return '<$' + $sprite + '>\n=='+$label+'' + $ftech + ''
    !endif
    !if ($descr != "") && ($sprite == "")
        !return '==' + $label + '' + $ftech + '\n\n '+$descr
    !endif
    !if ($descr != "") && ($sprite != "")
        !return '<$' + $sprite + '>\n==' + $label + $ftech + '\n\n '+$descr
    !endif
!endfunction

!procedure $tiAddToLegend($tag, $bgColor, $fontColor, $borderColor)
    !if (%function_exists("$addTagToDynamicLegend"))
        $addTagToDynamicLegend($tag, $bgColor, $fontColor, $borderColor)
    !endif
    !if (%function_exists("$addTagToLegend"))
        $addTagToLegend($tag, $bgColor, $fontColor, $borderColor)
    !endif
!endfunction

!unquoted procedure Queue($alias, $label, $descr="", $tech="", $sprite="", $tags="")
queue "$getQueue($label, $tech, $descr, $sprite)$getProps()" $toStereos("queue", $tags) as $alias
$tiAddToLegend(queue, $QUEUE_BG_COLOR, $QUEUE_FONT_COLOR, $QUEUE_BORDER_COLOR)
!endprocedure

!unquoted procedure App($alias, $label, $tech, $descr, $tags="")
rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[$tech]</size>//\n\n$descr\n<$mobile{scale=0.75}>" $toStereos('app', $tags) as $alias
$tiAddToLegend(app, $SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, $SYSTEM_BORDER_COLOR)
!endprocedure

!unquoted procedure App_iOS($alias, $label, $descr, $tags="")
rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[iOS]</size>//\n\n$descr\n<$apple{scale=0.75}>" $toStereos('app', $tags) as $alias
$tiAddToLegend(app_ios, $SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, $SYSTEM_BORDER_COLOR)
!endprocedure

!unquoted procedure App_Android($alias, $label, $descr, $tags="")
rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[Android]</size>//\n\n$descr\n<$android{scale=0.75}>" $toStereos('app', $tags) as $alias
$tiAddToLegend(app_android, $SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, $SYSTEM_BORDER_COLOR)
!endprocedure

!unquoted procedure Website($alias, $label, $tech, $descr, $tags="")
frame "==$label\n//<size:$TECHN_FONT_SIZE>[$tech]</size>//\n\n$descr\n<$chrome{scale=0.525}>" $toStereos('app', $tags) as $alias
$tiAddToLegend(website, $SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, "")
!endprocedure

!unquoted procedure Bot($alias, $label, $tech, $descr)
rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[$tech]</size>//\n\n$descr\n<$robot{scale=0.6}>" $toStereos("bot", $tags) as $alias
$tiAddToLegend(bot, $CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $CONTAINER_BORDER_COLOR)
!endprocedure

!define Rel_Both(e_from, e_to, e_label) Rel_(e_from, e_to, e_label, "<<-->>")
!define Rel_Both(e_from, e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "<<-->>")
!define Rel_Both_Neighbor(e_from, e_to, e_label) Rel_(e_from, e_to, e_label, "<<->>")
!define Rel_Both_Neighbor(e_from, e_to, e_label, e_techn) Rel_(e_from, e_to, e_label, e_techn, "<<->>")

!unquoted procedure BiRel_Neighbor($from, $to, $label)
Rel_($from, $to, $label, "<<->>")
!endprocedure
!unquoted procedure BiRel_Neighbor($from, $to, $label, $techn)
Rel_($from, $to, $label, $techn, "<<->>")
!endprocedure

!unquoted procedure Group()
Boundary(" ", " ", "group")
!endprocedure

!unquoted procedure Group(e_label)
rectangle "e_label" <<group>>
!endprocedure

!unquoted procedure Group(e_alias, e_label)
rectangle "e_label" <<group>> as e_alias
!endprocedure

!unquoted procedure SystemDb($alias, $label, $techn, $descr="", $sprite="", $tags="")
database "$getContainer($label, $techn, $descr, $sprite)$getProps()" $toStereos("system", $tags) as $alias
!endprocedure
